// tslint:disable
/**
 * Official Assignee Service Information System v4 (OASIS4)
 * This version  (1.3.1) contains  - basic searches of the registers (plural)   - claims functionality   - contacts functionality  - a PLACEHOLDER for estates fucnionality which is NOT CANONICAL   
 *
 * OpenAPI spec version: 1.3.1
 * Contact: sam@pxp.nz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
